declare namespace pins {
    //% fixedInstance shim=pxt::getPin(PIN_LED)
    const LED: PwmPin;

    //% fixedInstance shim=pxt::getPin(PIN_P0)
    const P0: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P1)
    const P1: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P2)
    const P2: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P3)
    const P3: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P4)
    const P4: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P5)
    const P5: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P6)
    const P6: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P7)
    const P7: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P8)
    const P8: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P9)
    const P9: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P10)
    const P10: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P11)
    const P11: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P12)
    const P12: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P13)
    const P13: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P14)
    const P14: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P15)
    const P15: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P16)
    const P16: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P17)
    const P17: PwmPin;

    //% fixedInstance shim=pxt::getPin(PIN_P18)
    const P18: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P19)
    const P19: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P20)
    const P20: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P21)
    const P21: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P26)
    const P26: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P33)
    const P33: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P34)
    const P34: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P35)
    const P35: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P36)
    const P36: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P37)
    const P37: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P38)
    const P38: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P39)
    const P39: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P40)
    const P40: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P41)
    const P41: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P42)
    const P42: PwmPin;

    //% fixedInstance shim=pxt::getPin(PIN_TX)
    const TX: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_RX)
    const RX: PwmPin;

    //% fixedInstance shim=pxt::getPin(PIN_P45)
    const P45: PwmPin;
    //% fixedInstance shim=pxt::getPin(PIN_P46)
    const P46: PwmOnlyPin;
    
}
